import { useState } from 'react';
import { motion } from 'framer-motion';
import { Link } from 'react-router-dom';
import { Mic, PlayCircle, MessageSquare, ChevronRight, Check } from 'lucide-react';

export default function InterviewPrep() {
  const [activeTab, setActiveTab] = useState('technical');
  const [currentQ, setCurrentQ] = useState(0);

  const questions = {
    technical: [
      { q: "Explain the virtual DOM in React.", difficulty: "Medium", completed: true },
      { q: "How do you handle state in a large application?", difficulty: "Hard", completed: false },
      { q: "What are React Hooks and why were they introduced?", difficulty: "Easy", completed: false }
    ],
    hr: [
      { q: "Tell me about a time you disagreed with a team member.", difficulty: "Medium", completed: false },
      { q: "Why do you want to work at our company?", difficulty: "Easy", completed: false }
    ]
  };

  const activeQuestions = questions[activeTab];

  return (
    <div className="min-h-screen bg-slate-950 text-slate-100 p-8 flex justify-center">
      <div className="w-full max-w-5xl relative z-10">
        
        <div className="flex items-center justify-between mb-8">
          <Link to="/dashboard" className="text-slate-400 hover:text-white transition-colors">
            &larr; Back to Dashboard
          </Link>
          <div className="bg-slate-900 p-1 rounded-lg border border-slate-800 flex">
            <button 
              onClick={() => setActiveTab('technical')}
              className={`px-6 py-2 rounded-md text-sm font-medium transition-all ${activeTab === 'technical' ? 'bg-blue-600 text-white shadow-lg' : 'text-slate-400 hover:text-slate-200'}`}
            >
              Technical Rounds
            </button>
            <button 
              onClick={() => setActiveTab('hr')}
              className={`px-6 py-2 rounded-md text-sm font-medium transition-all ${activeTab === 'hr' ? 'bg-blue-600 text-white shadow-lg' : 'text-slate-400 hover:text-slate-200'}`}
            >
              HR / Behavioral
            </button>
          </div>
        </div>

        <div className="grid md:grid-cols-3 gap-6">
          
          {/* Question List Sidebar */}
          <div className="bg-slate-900 border border-slate-800 rounded-2xl overflow-hidden flex flex-col h-[600px]">
            <div className="p-4 border-b border-slate-800 bg-slate-950/50">
              <h3 className="font-bold text-lg">Question Bank</h3>
              <p className="text-slate-500 text-sm">Generated by AI based on your resume</p>
            </div>
            <div className="overflow-y-auto flex-1 p-2 space-y-1">
              {activeQuestions.map((item, idx) => (
                <button 
                  key={idx}
                  onClick={() => setCurrentQ(idx)}
                  className={`w-full text-left p-4 rounded-xl border flex items-start gap-3 transition-colors ${currentQ === idx ? 'bg-blue-600/10 border-blue-600/30' : 'bg-transparent border-transparent hover:bg-slate-800'}`}
                >
                  <div className={`mt-0.5 flex-shrink-0 w-5 h-5 rounded-full border flex items-center justify-center ${item.completed ? 'bg-emerald-500/20 border-emerald-500/50 text-emerald-500' : 'border-slate-700'}`}>
                    {item.completed && <Check size={12} strokeWidth={3} />}
                  </div>
                  <div>
                    <p className={`text-sm ${currentQ === idx ? 'text-white font-medium' : 'text-slate-300'}`}>{item.q}</p>
                    <span className={`text-[10px] mt-2 inline-block px-2 py-0.5 rounded border ${
                      item.difficulty === 'Hard' ? 'bg-rose-500/10 border-rose-500/20 text-rose-400' :
                      item.difficulty === 'Medium' ? 'bg-amber-500/10 border-amber-500/20 text-amber-400' :
                      'bg-emerald-500/10 border-emerald-500/20 text-emerald-400'
                    }`}>
                      {item.difficulty}
                    </span>
                  </div>
                </button>
              ))}
            </div>
          </div>

          {/* Active Interview Area */}
          <div className="md:col-span-2 bg-slate-900 border border-slate-800 rounded-2xl flex flex-col h-[600px] relative overflow-hidden">
            <div className="absolute top-0 right-0 w-64 h-64 bg-blue-600/5 blur-3xl rounded-full mix-blend-screen pointer-events-none"></div>
            
            <div className="p-8 flex-1 flex flex-col justify-center items-center text-center">
              <span className="text-blue-500 font-bold tracking-widest text-xs uppercase mb-4">Question {currentQ + 1} of {activeQuestions.length}</span>
              <h2 className="text-2xl md:text-3xl font-bold text-white leading-tight mb-8">
                "{activeQuestions[currentQ].q}"
              </h2>
            </div>
            
            <div className="bg-slate-950/50 p-6 border-t border-slate-800">
              <div className="flex items-center justify-center gap-4">
                <button className="flex flex-col items-center gap-2 group">
                  <div className="w-16 h-16 rounded-full bg-slate-800 flex items-center justify-center border border-slate-700 group-hover:bg-slate-700 transition-colors">
                    <MessageSquare size={24} className="text-slate-300 group-hover:text-white" />
                  </div>
                  <span className="text-xs text-slate-400 font-medium">Type Answer</span>
                </button>
                
                <div className="w-px h-12 bg-slate-800 mx-4"></div>

                <button className="flex flex-col items-center gap-2 group relative">
                  <div className="absolute inset-0 bg-blue-500 rounded-full blur-md opacity-20 group-hover:opacity-40 transition-opacity"></div>
                  <div className="w-20 h-20 rounded-full bg-blue-600 flex items-center justify-center relative z-10 group-hover:scale-105 transition-transform shadow-[0_0_20px_rgba(37,99,235,0.4)]">
                    <Mic size={32} className="text-white" />
                  </div>
                  <span className="text-xs text-blue-400 font-medium mt-1">Start Recording</span>
                </button>
              </div>
            </div>
          </div>

        </div>
      </div>
    </div>
  );
}
